name: Run getCitation Script

on:
  schedule:
    - cron: '00 * * * *'
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run getCitation.py script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python getCitation.py
        working-directory: ./scripts

      - name: Commit and push if changes
        run: |
          git config --global user.email "mayingpeng33@gmail.com"
          git config --global user.name "yingpengma"
          git add -f scripts/citationCount.json
          # Only commit if there were changes
          git diff --staged --quiet || (git commit -m "Update citationCount.json" && git push)
