name: Run getCitation Script

on:
  schedule:
    # 每小时执行一次
    - cron: '05 * * * *'
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run getCitation.py script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python scripts/getCitation.py
